version: "3"

volumes:
  database:
    driver: local

services:
  postgres:
    image: postgres:16-alpine
    container_name: adorablee_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: adorable
      POSTGRES_PASSWORD: adorable
      POSTGRES_DB: adorable
    volumes:
      - database:/var/lib/postgresql/data
